/**
 * 
 */
/**
 * @author RANIEL E AMANDA
 * @version SEGUNDO ENVIO DAS PRÁTICAS DE POO2
 *	PROFESSOR HENRIQUE, BCC - UFU, 2017-01
 *	PRÁTICA 7 - PADRÃO FACTORY METHOD
 *	PROBLEMA - CRIAR UMA FÁBRICA DE CADEIAS NA PRÁTICA 04, NÃO MOSTRANDO AS CÉDULAS CUJA QUANTIDADE É 0
 *
 */
package pratica07;