/**
 * 
 */
/**
 * @author Raniel e Amanda
 * @version SEGUNDO ENVIO DAS PRÁTICAS DE POO2
 *	PROFESSOR HENRIQUE, BCC - UFU, 2017-01
 *	PRÁTICA 10 - PADRÃO TEMPLATE METHOD
 *	PROBLEMA - ABRIR 3 TIPOS DE CONTAS DIFERENTES EM UM BANCO
 *
 */
package pratica10;