/**
 * 
 */
/**
 * @author RANIEL E AMANDA
 *	SEGUNDO ENVIO DAS PRÁTICAS DE POO2
 *	PROFESSOR HENRIQUE, BCC - UFU, 2017-01
 *	PRÁTICA 7 - PADRÃO FACTORY METHOD
 *	PROBLEMA - GERAR AS CADEIAS DA PRÁTICA 04 ATRAVÉS DESSE MÉTODO
 *
 */
package pratica7;